name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Check if src/cli.ts exists
        run: |
          if [ -f "src/cli.ts" ]; then
            echo "NODE_CLI=true" >> $GITHUB_ENV
          else
            echo "NODE_CLI=false" >> $GITHUB_ENV
          fi

      - name: Setup Deno
        if: env.NODE_CLI == 'true'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.4

      - name: Compile CLI
        if: env.NODE_CLI == 'true'
        run: |
          deno bundle --platform deno --minify --output ./src/cli.js ./src/cli.ts

      - name: Publish package
        run: npx jsr publish --allow-dirty
